name: '1 - Deploy DB to Azure Region A'

on:
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Production
    env: 
      backend-path: 'backendA.tfvars'
      location: 'EastUS'
      RG: "databricksdemo-A"


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: |
        terraform init -backend-config ${{env.backend-path}}

    - name: Terraform plan
      run: terraform plan -var=rg='${{env.RG}}'

    - name: Terraform apply
      run: terraform apply -var=rg='${{env.RG}}' -auto-approve
