name: '1 - Deploy DB to Azure Region A'

on:
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Production
    env: 
      backend-path: 'backendA.tfvars'
      location: 'EastUS'
      RG: "databricksdemo-A"


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: show env
      run: |
        echo "ACTIONS_ID_TOKEN_REQUEST_URL = $ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN = $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

    - name: Terraform init
      run: |      
        terraform init -backend-config ${{env.backend-path}} \
          -backend-config tenant_id=${{ secrets.AZURE_TENANT_ID }} \
          -backend-config client_id=${{ secrets.AZURE_CLIENT_ID }} \
          -backend-config subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform plan
      run: terraform plan -var=rg='${{env.RG}}'

    - name: Terraform apply
      run: terraform apply -var=rg='${{env.RG}}' -auto-approve
