name: '99 -- Test azure login with cli action'

on:
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true
  


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Production
    env: 
      backend-path: 'backendB.tfvars'
      location: 'EastUS'
      RG: "databricksdemo-B"


    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        # azcliversion: 2.30.0
        inlineScript: |
          az account list
          az login 
          az account list


    - run:  az account list

    # # Logs in with your Azure credentials
    # - name: Azure login
    #   uses: azure/login@v1.4.6
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

   